package com.example.project.enums;

public enum NotificationType {
    COMMENT_CREATED,
    POST_CREATED,
    POST_LIKED,
    POST_COMMENTED,
    STORY_CREATED,
    STORY_VIEWED,
    PROFILE_CREATED,
    PROFILE_FOLLOWED,
    COMMENT_LIKED, COMMENT_REATED, SUBSCRIPTION_NEW
}
